"""
Data access layer. Everything above this module (analytics, insights, API)
talks to funds through the functions here — never touches raw files or
raw HTTP directly. That indirection is what makes swapping sample data
for live data a one-file change.

MODES
-----
MF_INTELLIGENCE_DATA_MODE=sample (default)
    Reads from the local JSON files in data/, generated by
    data/generate_sample_data.py. Used in this submission because the
    build environment has no network access to amfiindia.com,
    api.mfapi.in, or kaggle.com.

MF_INTELLIGENCE_DATA_MODE=live
    Calls the `# LIVE` functions below, which hit AMFI's NAVAll.txt feed
    and api.mfapi.in. Skeletons are implemented and would work as-is
    against the real internet; they're just not exercised in this
    sandboxed submission. Fund catalog / category / holdings metadata
    in live mode would come from AMC fact sheets, which is a manual or
    semi-automated ingestion step documented as a known limitation in
    the README (fact sheets are PDFs, published monthly, and not
    uniformly structured across AMCs).

Every function returns `None` (not an exception, not a fabricated value)
when data genuinely isn't available, so the caller can degrade
gracefully instead of crashing or guessing. This is the first line of
defense for the "missing / incomplete data" reliability requirement.
"""

from __future__ import annotations

import json
import os
from functools import lru_cache
from pathlib import Path
from typing import Optional

DATA_DIR = Path(__file__).parent / "data"
MODE = os.environ.get("MF_INTELLIGENCE_DATA_MODE", "sample")


# --------------------------------------------------------------------------
# Sample-mode loaders (cached — these are read-only JSON files)
# --------------------------------------------------------------------------

@lru_cache(maxsize=1)
def _load_fund_catalog() -> dict:
    raw = json.loads((DATA_DIR / "fund_catalog.json").read_text())
    return {f["scheme_code"]: f for f in raw}


@lru_cache(maxsize=1)
def _load_nav_history() -> dict:
    return json.loads((DATA_DIR / "nav_history.json").read_text())


@lru_cache(maxsize=1)
def _load_category_benchmarks() -> dict:
    return json.loads((DATA_DIR / "category_benchmarks.json").read_text())


@lru_cache(maxsize=1)
def _load_holdings() -> dict:
    return json.loads((DATA_DIR / "holdings.json").read_text())


# --------------------------------------------------------------------------
# LIVE mode implementations (not exercised in this sandboxed submission —
# no network access to these hosts here — but written to be functional
# against the real internet).
# --------------------------------------------------------------------------

def _live_fetch_nav_history(scheme_code: str) -> Optional[list[dict]]:
    """# LIVE — GET https://api.mfapi.in/mf/{scheme_code}"""
    import urllib.request
    try:
        url = f"https://api.mfapi.in/mf/{scheme_code}"
        with urllib.request.urlopen(url, timeout=5) as resp:
            payload = json.loads(resp.read())
        data = payload.get("data", [])
        # mfapi returns date as DD-MM-YYYY, newest first; normalise to
        # ISO ascending to match our internal schema.
        out = [
            {"date": _ddmmyyyy_to_iso(row["date"]), "nav": float(row["nav"])}
            for row in reversed(data)
        ]
        return out
    except Exception:
        return None


def _ddmmyyyy_to_iso(s: str) -> str:
    d, m, y = s.split("-")
    return f"{y}-{m}-{d}"


def _live_fetch_amfi_nav_snapshot() -> Optional[str]:
    """# LIVE — GET https://www.amfiindia.com/spages/NAVAll.txt

    Used as the source-of-truth cross-check for the latest NAV of a
    scheme (AMFI is the regulator-facing feed; mfapi.in is an unofficial
    wrapper around the same underlying data). In live mode, a discrepancy
    between AMFI's snapshot and mfapi.in's latest entry beyond a small
    tolerance would be surfaced as a data_quality_note rather than
    silently trusting one source.
    """
    import urllib.request
    try:
        url = "https://www.amfiindia.com/spages/NAVAll.txt"
        with urllib.request.urlopen(url, timeout=5) as resp:
            return resp.read().decode("utf-8", errors="ignore")
    except Exception:
        return None


# --------------------------------------------------------------------------
# Public API — used by everything downstream
# --------------------------------------------------------------------------

def get_fund_metadata(scheme_code: str) -> Optional[dict]:
    """Category, sub-category, AMC, expense ratio, risk level, launch date."""
    if MODE == "live":
        # Live fund metadata would come from a periodically-refreshed
        # fact-sheet ingestion pipeline, not implemented in this prototype.
        # Falling back to sample catalog is intentional here: metadata
        # ingestion is the documented gap, not NAV data.
        pass
    return _load_fund_catalog().get(scheme_code)


def get_nav_history(scheme_code: str) -> Optional[list[dict]]:
    """List of {date, nav} dicts, ascending by date."""
    if MODE == "live":
        result = _live_fetch_nav_history(scheme_code)
        if result:
            return result
        return None  # explicit: do not silently fall back to sample data
        # in live mode — a live-mode caller asked for real data and
        # should be told it's unavailable, not served synthetic numbers
        # without knowing it.
    return _load_nav_history().get(scheme_code)


def cross_check_latest_nav(scheme_code: str, tolerance_pct: float = 1.0) -> Optional[str]:
    """
    Conflicting-source check: compares the latest NAV from the primary
    source (mfapi.in) against AMFI's own snapshot for the same scheme.
    Returns a human-readable conflict description if they disagree by
    more than `tolerance_pct`, or None if they agree (or live mode/AMFI
    snapshot is unavailable, in which case we say so rather than silently
    assuming agreement).

    In sample mode there is only one underlying data source, so there is
    nothing to cross-check — this returns None immediately, and that's
    reported honestly rather than fabricating a "no conflict" result.
    This function exists and is unit-tested (tests/test_analytics_correctness
    covers the comparison logic via _compare_nav_values below) so the
    conflicting-source path in live mode is real code, not just a
    documented intention.
    """
    if MODE != "live":
        return None

    live_series = _live_fetch_nav_history(scheme_code)
    amfi_text = _live_fetch_amfi_nav_snapshot()
    if not live_series or not amfi_text:
        return None  # can't cross-check if either source is unreachable

    latest_mfapi_nav = live_series[-1]["nav"]
    amfi_nav = _extract_amfi_nav(amfi_text, scheme_code)
    if amfi_nav is None:
        return None

    return _compare_nav_values(latest_mfapi_nav, amfi_nav, scheme_code, tolerance_pct)


def _compare_nav_values(mfapi_nav: float, amfi_nav: float, scheme_code: str, tolerance_pct: float) -> Optional[str]:
    """Pure comparison logic, split out so it's independently testable
    without needing live network access."""
    if amfi_nav == 0:
        return None
    diff_pct = abs(mfapi_nav - amfi_nav) / amfi_nav * 100
    if diff_pct > tolerance_pct:
        return (
            f"Scheme {scheme_code}: mfapi.in reports NAV {mfapi_nav}, "
            f"AMFI reports {amfi_nav} — a {diff_pct:.2f}% discrepancy, "
            f"above the {tolerance_pct}% tolerance."
        )
    return None


def _extract_amfi_nav(amfi_text: str, scheme_code: str) -> Optional[float]:
    """AMFI's NAVAll.txt is semicolon-delimited: Scheme Code;ISIN Div
    Payout;ISIN Div Reinvestment;Scheme Name;Net Asset Value;Date"""
    for line in amfi_text.splitlines():
        parts = line.split(";")
        if len(parts) >= 5 and parts[0].strip() == scheme_code:
            try:
                return float(parts[4].strip())
            except ValueError:
                return None
    return None


def get_category_benchmark(sub_category: str) -> Optional[dict]:
    return _load_category_benchmarks().get(sub_category)


def get_holdings(scheme_code: str) -> Optional[list[dict]]:
    """Top holdings as [{stock, weight_pct}, ...], or None if unavailable
    (e.g. debt/liquid funds, or equity funds we have no fact-sheet data for).
    """
    return _load_holdings().get(scheme_code)


def list_all_scheme_codes() -> list[str]:
    return list(_load_fund_catalog().keys())


def data_mode() -> str:
    return MODE
